"""added currency in country

Revision ID: 046f3d0e2f4b
Revises: e94abaf727be
Create Date: 2025-05-08 17:43:15.010677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '046f3d0e2f4b'
down_revision: Union[str, None] = 'e94abaf727be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'currency')
    # ### end Alembic commands ###
