"""added image in quiz

Revision ID: 0aded128033a
Revises: 1535161f8232
Create Date: 2025-05-19 11:56:20.175623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aded128033a'
down_revision: Union[str, None] = '1535161f8232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_questions', sa.Column('image_url', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_questions', 'image_url')
    # ### end Alembic commands ###
