"""changed qualification to key_qualification

Revision ID: 30e0ddb19c75
Revises: 4137aa0ea881
Create Date: 2025-05-06 18:43:56.186444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30e0ddb19c75'
down_revision: Union[str, None] = '4137aa0ea881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('key_qualification', sa.String(), nullable=True))
    op.drop_column('jobs', 'qualification')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('qualification', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'key_qualification')
    # ### end Alembic commands ###
