"""updated quiz option model

Revision ID: 45bf2a725705
Revises: 5659345b84a5
Create Date: 2025-04-22 14:16:56.017091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45bf2a725705'
down_revision: Union[str, None] = '5659345b84a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dsa_test_case_responses', sa.Column('task_id', sa.String(), nullable=True))
    op.add_column('quiz_options', sa.Column('correct', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_options', 'correct')
    op.drop_column('dsa_test_case_responses', 'task_id')
    # ### end Alembic commands ###
