"""made interview unique on email

Revision ID: 4d3530431157
Revises: 546661d06e9c
Create Date: 2025-04-13 12:17:46.794584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d3530431157'
down_revision: Union[str, None] = '546661d06e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_email_job', 'interviews', ['email', 'job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_email_job', 'interviews', type_='unique')
    # ### end Alembic commands ###
