"""added verification status for recruiter

Revision ID: 546661d06e9c
Revises: 573cc2c61938
Create Date: 2025-04-11 10:26:04.953269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '546661d06e9c'
down_revision: Union[str, None] = '573cc2c61938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruiters', sa.Column('verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruiters', 'verified')
    # ### end Alembic commands ###
