"""added skills breakdown in interview model

Revision ID: 5659345b84a5
Revises: 753a2b26635b
Create Date: 2025-04-22 11:10:16.719415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5659345b84a5'
down_revision: Union[str, None] = '753a2b26635b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('technical_skills_score', sa.Integer(), nullable=True))
    op.add_column('interviews', sa.Column('communication_skills_score', sa.Integer(), nullable=True))
    op.add_column('interviews', sa.Column('problem_solving_skills_score', sa.Integer(), nullable=True))
    op.add_column('interviews', sa.Column('cultural_fit_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'cultural_fit_score')
    op.drop_column('interviews', 'problem_solving_skills_score')
    op.drop_column('interviews', 'communication_skills_score')
    op.drop_column('interviews', 'technical_skills_score')
    # ### end Alembic commands ###
