"""added cascade delete

Revision ID: 72b2bee87215
Revises: 6a231a827d2f
Create Date: 2025-04-23 10:03:26.180101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72b2bee87215'
down_revision: Union[str, None] = '6a231a827d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dsa_questions_job_id_fkey', 'dsa_questions', type_='foreignkey')
    op.create_foreign_key(None, 'dsa_questions', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('dsa_responses_interview_id_fkey', 'dsa_responses', type_='foreignkey')
    op.drop_constraint('dsa_responses_question_id_fkey', 'dsa_responses', type_='foreignkey')
    op.create_foreign_key(None, 'dsa_responses', 'interviews', ['interview_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dsa_responses', 'dsa_questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('dsa_test_case_responses_dsa_response_id_fkey', 'dsa_test_case_responses', type_='foreignkey')
    op.drop_constraint('dsa_test_case_responses_dsa_test_case_id_fkey', 'dsa_test_case_responses', type_='foreignkey')
    op.create_foreign_key(None, 'dsa_test_case_responses', 'dsa_test_cases', ['dsa_test_case_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dsa_test_case_responses', 'dsa_responses', ['dsa_response_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('dsa_test_cases_dsa_question_id_fkey', 'dsa_test_cases', type_='foreignkey')
    op.create_foreign_key(None, 'dsa_test_cases', 'dsa_questions', ['dsa_question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('interview_question_and_responses_interview_id_fkey', 'interview_question_and_responses', type_='foreignkey')
    op.create_foreign_key(None, 'interview_question_and_responses', 'interviews', ['interview_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('interviews_job_id_fkey', 'interviews', type_='foreignkey')
    op.create_foreign_key(None, 'interviews', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('jobs_company_id_fkey', 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'recruiters', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('quiz_options_question_id_fkey', 'quiz_options', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_options', 'quiz_questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('quiz_questions_job_id_fkey', 'quiz_questions', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_questions', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('quiz_responses_interview_id_fkey', 'quiz_responses', type_='foreignkey')
    op.drop_constraint('quiz_responses_question_id_fkey', 'quiz_responses', type_='foreignkey')
    op.drop_constraint('quiz_responses_option_id_fkey', 'quiz_responses', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_responses', 'quiz_options', ['option_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'quiz_responses', 'interviews', ['interview_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'quiz_responses', 'quiz_questions', ['question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_responses', type_='foreignkey')
    op.drop_constraint(None, 'quiz_responses', type_='foreignkey')
    op.drop_constraint(None, 'quiz_responses', type_='foreignkey')
    op.create_foreign_key('quiz_responses_option_id_fkey', 'quiz_responses', 'quiz_options', ['option_id'], ['id'])
    op.create_foreign_key('quiz_responses_question_id_fkey', 'quiz_responses', 'quiz_questions', ['question_id'], ['id'])
    op.create_foreign_key('quiz_responses_interview_id_fkey', 'quiz_responses', 'interviews', ['interview_id'], ['id'])
    op.drop_constraint(None, 'quiz_questions', type_='foreignkey')
    op.create_foreign_key('quiz_questions_job_id_fkey', 'quiz_questions', 'jobs', ['job_id'], ['id'])
    op.drop_constraint(None, 'quiz_options', type_='foreignkey')
    op.create_foreign_key('quiz_options_question_id_fkey', 'quiz_options', 'quiz_questions', ['question_id'], ['id'])
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key('jobs_company_id_fkey', 'jobs', 'recruiters', ['company_id'], ['id'])
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.create_foreign_key('interviews_job_id_fkey', 'interviews', 'jobs', ['job_id'], ['id'])
    op.drop_constraint(None, 'interview_question_and_responses', type_='foreignkey')
    op.create_foreign_key('interview_question_and_responses_interview_id_fkey', 'interview_question_and_responses', 'interviews', ['interview_id'], ['id'])
    op.drop_constraint(None, 'dsa_test_cases', type_='foreignkey')
    op.create_foreign_key('dsa_test_cases_dsa_question_id_fkey', 'dsa_test_cases', 'dsa_questions', ['dsa_question_id'], ['id'])
    op.drop_constraint(None, 'dsa_test_case_responses', type_='foreignkey')
    op.drop_constraint(None, 'dsa_test_case_responses', type_='foreignkey')
    op.create_foreign_key('dsa_test_case_responses_dsa_test_case_id_fkey', 'dsa_test_case_responses', 'dsa_test_cases', ['dsa_test_case_id'], ['id'])
    op.create_foreign_key('dsa_test_case_responses_dsa_response_id_fkey', 'dsa_test_case_responses', 'dsa_responses', ['dsa_response_id'], ['id'])
    op.drop_constraint(None, 'dsa_responses', type_='foreignkey')
    op.drop_constraint(None, 'dsa_responses', type_='foreignkey')
    op.create_foreign_key('dsa_responses_question_id_fkey', 'dsa_responses', 'dsa_questions', ['question_id'], ['id'])
    op.create_foreign_key('dsa_responses_interview_id_fkey', 'dsa_responses', 'interviews', ['interview_id'], ['id'])
    op.drop_constraint(None, 'dsa_questions', type_='foreignkey')
    op.create_foreign_key('dsa_questions_job_id_fkey', 'dsa_questions', 'jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###
