"""updated dsa question model

Revision ID: 753a2b26635b
Revises: f08f85e218e5
Create Date: 2025-04-22 09:22:50.954168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '753a2b26635b'
down_revision: Union[str, None] = 'f08f85e218e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dsa_questions', sa.Column('title', sa.String(), nullable=True))
    op.add_column('dsa_questions', sa.Column('difficulty', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dsa_questions', 'difficulty')
    op.drop_column('dsa_questions', 'title')
    # ### end Alembic commands ###
