"""added email verified status in recruiter model

Revision ID: 8171e7cefcd7
Revises: 87e8a9de11d2
Create Date: 2025-04-30 13:23:31.098663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8171e7cefcd7'
down_revision: Union[str, None] = '87e8a9de11d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruiters', sa.Column('email_otp', sa.String(), nullable=True))
    op.add_column('recruiters', sa.Column('email_otp_expiry', sa.DateTime(), nullable=True))
    op.add_column('recruiters', sa.Column('email_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruiters', 'email_verified')
    op.drop_column('recruiters', 'email_otp_expiry')
    op.drop_column('recruiters', 'email_otp')
    # ### end Alembic commands ###
