"""added email otp fields in interview model

Revision ID: 82a4b6582def
Revises: cf4d5187959a
Create Date: 2025-05-12 15:39:56.308344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82a4b6582def'
down_revision: Union[str, None] = 'cf4d5187959a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('email_otp', sa.String(), nullable=True))
    op.add_column('interviews', sa.Column('email_otp_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'email_otp_expiry')
    op.drop_column('interviews', 'email_otp')
    # ### end Alembic commands ###
