"""checking unique constraint

Revision ID: 87e8a9de11d2
Revises: f3992dcd8982
Create Date: 2025-04-25 17:32:52.013804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87e8a9de11d2'
down_revision: Union[str, None] = 'f3992dcd8982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_interview_and_question', 'dsa_responses', ['interview_id', 'question_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_interview_and_question', 'dsa_responses', type_='unique')
    # ### end Alembic commands ###
