"""added quiz and dsa schema

Revision ID: a6012b42f02b
Revises: 4d3530431157
Create Date: 2025-04-18 14:33:16.846062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6012b42f02b'
down_revision: Union[str, None] = '4d3530431157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dsa_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dsa_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('interview_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['dsa_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dsa_test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input', sa.String(), nullable=True),
    sa.Column('expected_output', sa.String(), nullable=True),
    sa.Column('dsa_question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dsa_question_id'], ['dsa_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_responses',
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.ForeignKeyConstraint(['option_id'], ['quiz_questions.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.PrimaryKeyConstraint('interview_id', 'question_id')
    )
    op.create_table('dsa_test_case_responses',
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('dsa_response_id', sa.Integer(), nullable=False),
    sa.Column('dsa_test_case_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dsa_response_id'], ['dsa_responses.id'], ),
    sa.ForeignKeyConstraint(['dsa_test_case_id'], ['dsa_test_cases.id'], ),
    sa.PrimaryKeyConstraint('dsa_response_id', 'dsa_test_case_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dsa_test_case_responses')
    op.drop_table('quiz_responses')
    op.drop_table('quiz_options')
    op.drop_table('dsa_test_cases')
    op.drop_table('dsa_responses')
    op.drop_table('quiz_questions')
    op.drop_table('dsa_questions')
    # ### end Alembic commands ###
