"""updated countries with currency

Revision ID: cf4d5187959a
Revises: 046f3d0e2f4b
Create Date: 2025-05-08 17:44:30.697514

"""

import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session

from app.models import Country


# revision identifiers, used by Alembic.
revision: str = "cf4d5187959a"
down_revision: Union[str, None] = "046f3d0e2f4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)

    with open("alembic/currency.json", encoding="utf-8") as f:
        data = json.load(f)

    for d in data:
        stmt = (
            sa.update(Country)
            .where(Country.id == d["id"])
            .values(currency=d["currency"])
        )

        session.execute(stmt)

    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
