"""added answer field in interview question response

Revision ID: e36a62b79935
Revises: 219f9734a460
Create Date: 2025-05-21 16:19:50.235006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36a62b79935'
down_revision: Union[str, None] = '219f9734a460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_question_responses', sa.Column('answer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_question_responses', 'answer')
    # ### end Alembic commands ###
