"""populated country, state, city

Revision ID: e94abaf727be
Revises: a3c862175f68
Create Date: 2025-05-08 10:25:53.904447

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
import json

from app.models import City, Country, State


# revision identifiers, used by Alembic.
revision: str = "e94abaf727be"
down_revision: Union[str, None] = "a3c862175f68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)

    with open("alembic/countries.json", encoding="utf-8") as f:
        data = json.load(f)

    countries = [Country(**item) for item in data]
    session.add_all(countries)

    with open("alembic/states.json", encoding="utf-8") as f:
        data = json.load(f)

    states = [State(**item) for item in data]
    session.add_all(states)

    with open("alembic/cities.json", encoding="utf-8") as f:
        data = json.load(f)

    cities = [City(**item) for item in data]
    session.add_all(cities)

    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)

    session.query(Country).delete(synchronize_session=False)
    session.query(State).delete(synchronize_session=False)
    session.query(City).delete(synchronize_session=False)

    session.commit()
    # ### end Alembic commands ###
