"""added city in job table

Revision ID: f08f85e218e5
Revises: a6012b42f02b
Create Date: 2025-04-21 14:59:48.824416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f08f85e218e5'
down_revision: Union[str, None] = 'a6012b42f02b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('city', sa.String(), nullable=True))
    op.drop_constraint('quiz_responses_option_id_fkey', 'quiz_responses', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_responses', 'quiz_options', ['option_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_responses', type_='foreignkey')
    op.create_foreign_key('quiz_responses_option_id_fkey', 'quiz_responses', 'quiz_questions', ['option_id'], ['id'])
    op.drop_column('jobs', 'city')
    # ### end Alembic commands ###
